# Generated by Django 5.2 on 2025-04-04 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_editors',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_viewers',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que pueden consultar los registros de este editor', related_name='can_view_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Consultor')], max_length=10),
        ),
    ]
