# Generated by Django 5.2 on 2025-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0002_remove_userprofile_allowed_editors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='programas_p',
            fields=[
                ('id_pp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pp', models.CharField(max_length=255)),
            ],
        ),
    ]
