# Generated by Django 5.2 on 2025-04-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0003_programas_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='arbol_problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_indirecta', models.CharField(max_length=255)),
                ('causa_directa', models.CharField(max_length=255)),
                ('problema_principal', models.CharField(max_length=255)),
                ('efecto_directo', models.CharField(max_length=255)),
                ('efecto_indirecto', models.CharField(max_length=255)),
                ('efecto_superior', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
    ]
