# Generated by Django 5.2 on 2025-04-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0005_permisos_pps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaDirecta',
            fields=[
                ('id_CD', models.AutoField(primary_key=True, serialize=False)),
                ('causa_directa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CausaIndirecta',
            fields=[
                ('id_CI', models.AutoField(primary_key=True, serialize=False)),
                ('causa_indirecta', models.TextField()),
                ('id_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas_indirectas', to='PPRegister.causadirecta')),
            ],
        ),
        migrations.CreateModel(
            name='EfectoSuperior',
            fields=[
                ('id_ES', models.AutoField(primary_key=True, serialize=False)),
                ('efecto_superior', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efecto_superior', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='EfectoIndirecto',
            fields=[
                ('id_EI', models.AutoField(primary_key=True, serialize=False)),
                ('efecto_indirecto', models.TextField()),
                ('id_ES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efectos_indirectos', to='PPRegister.efectosuperior')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaCentral',
            fields=[
                ('id_PC', models.AutoField(primary_key=True, serialize=False)),
                ('problema_central', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problema_central', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='EfectoDirecto',
            fields=[
                ('id_ED', models.AutoField(primary_key=True, serialize=False)),
                ('efecto_directo', models.TextField()),
                ('id_EI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efectos_directos', to='PPRegister.efectoindirecto')),
                ('id_PC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efectos_directos', to='PPRegister.problemacentral')),
            ],
        ),
        migrations.AddField(
            model_name='causadirecta',
            name='id_PC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas_directas', to='PPRegister.problemacentral'),
        ),
        migrations.DeleteModel(
            name='arbol_problemas',
        ),
    ]
