# Generated by Django 5.2 on 2025-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0006_causadirecta_causaindirecta_efectosuperior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas_p',
            name='num_pp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
