# Generated by Django 5.2 on 2025-04-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0007_programas_p_num_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinSuperior',
            fields=[
                ('id_FS', models.AutoField(primary_key=True, serialize=False)),
                ('fin_superior', models.CharField(max_length=255)),
                ('id_ES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_superior', to='PPRegister.efectosuperior')),
            ],
        ),
        migrations.CreateModel(
            name='FinIndirecto',
            fields=[
                ('id_FI', models.AutoField(primary_key=True, serialize=False)),
                ('fin_indirecto', models.TextField()),
                ('id_EI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_indirecto', to='PPRegister.efectoindirecto')),
                ('id_FS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_indirecto', to='PPRegister.finsuperior')),
            ],
        ),
        migrations.CreateModel(
            name='MedioDirecto',
            fields=[
                ('id_MD', models.AutoField(primary_key=True, serialize=False)),
                ('medio_directo', models.TextField()),
                ('id_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_directo', to='PPRegister.causadirecta')),
            ],
        ),
        migrations.CreateModel(
            name='MedioIndirecto',
            fields=[
                ('id_MI', models.AutoField(primary_key=True, serialize=False)),
                ('medio_indirecto', models.TextField()),
                ('id_CI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_indirecto', to='PPRegister.causaindirecta')),
                ('id_MD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_indirecto', to='PPRegister.mediodirecto')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionProblema',
            fields=[
                ('id_SP', models.AutoField(primary_key=True, serialize=False)),
                ('solucion_problema', models.CharField(max_length=255)),
                ('id_PC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucion_problema', to='PPRegister.problemacentral')),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucion_problema', to='PPRegister.programas_p')),
            ],
        ),
        migrations.AddField(
            model_name='mediodirecto',
            name='id_SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_directo', to='PPRegister.solucionproblema'),
        ),
        migrations.CreateModel(
            name='FinDirecto',
            fields=[
                ('id_FD', models.AutoField(primary_key=True, serialize=False)),
                ('fin_directo', models.TextField()),
                ('id_ED', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_directo', to='PPRegister.efectodirecto')),
                ('id_FI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_directo', to='PPRegister.finindirecto')),
                ('id_SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_directo', to='PPRegister.solucionproblema')),
            ],
        ),
    ]
