# Generated by Django 5.2 on 2025-04-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0008_finsuperior_finindirecto_mediodirecto_medioindirecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findirecto',
            name='id_ED',
        ),
        migrations.RemoveField(
            model_name='finindirecto',
            name='id_EI',
        ),
        migrations.RemoveField(
            model_name='finsuperior',
            name='id_ES',
        ),
        migrations.RemoveField(
            model_name='mediodirecto',
            name='id_CD',
        ),
        migrations.RemoveField(
            model_name='medioindirecto',
            name='id_CI',
        ),
        migrations.RemoveField(
            model_name='solucionproblema',
            name='id_PC',
        ),
        migrations.AddField(
            model_name='finsuperior',
            name='id_pp',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='fin_superior', to='PPRegister.programas_p'),
        ),
    ]
