# Generated by Django 5.2 on 2025-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0009_remove_findirecto_id_ed_remove_finindirecto_id_ei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos_pps',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
