# Generated by Django 5.2 on 2025-04-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0010_permisos_pps_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('referencia', 'Población de Preferencia'), ('potencial', 'Población Potencial o Afectada'), ('objetivo', 'Población Objetivo'), ('postergada', 'Población Postergada')], max_length=20)),
                ('descripcion', models.TextField()),
                ('hombres', models.PositiveIntegerField(default=0)),
                ('mujeres', models.PositiveIntegerField(default=0)),
                ('hablantes_lengua', models.PositiveIntegerField(default=0)),
                ('grupos_edad', models.PositiveIntegerField(default=0)),
                ('medios_verificacion', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poblacion_objetivo', to='PPRegister.programas_p')),
            ],
        ),
    ]
