# Generated by Django 5.2 on 2025-05-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0011_poblacionobjetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id_objetivo_especifico', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo_especifico', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='poblacionobjetivo',
            name='tipo',
            field=models.CharField(choices=[('referencia', 'Población de Referencia'), ('potencial', 'Población Potencial o Afectada'), ('objetivo', 'Población Objetivo'), ('postergada', 'Población Postergada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programas_p',
            name='num_pp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Directriz',
            fields=[
                ('id_directriz', models.AutoField(primary_key=True, serialize=False)),
                ('directriz', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAccion',
            fields=[
                ('id_linea_accion', models.AutoField(primary_key=True, serialize=False)),
                ('linea_accion', models.CharField(max_length=255)),
                ('id_objetivo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.objetivoespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id_objetivo_estrategico', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo_estrategico', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='id_objetivo_estrategico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.objetivoestrategico'),
        ),
        migrations.CreateModel(
            name='Vertiente',
            fields=[
                ('id_vertiente', models.AutoField(primary_key=True, serialize=False)),
                ('vertiente', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
    ]
