# Generated by Django 5.2 on 2025-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0012_objetivoespecifico_alter_poblacionobjetivo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poblacionobjetivo',
            name='grupos_edad',
            field=models.TextField(),
        ),
    ]
