# Generated by Django 5.2 on 2025-05-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0013_alter_poblacionobjetivo_grupos_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.TextField()),
                ('descripcion', models.TextField()),
                ('criterio_calidad', models.TextField()),
                ('criterio', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes_servicios', to='PPRegister.programas_p')),
            ],
        ),
    ]
