# Generated by Django 5.2 on 2025-05-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0014_bienservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteMir',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadMir',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255)),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='PPRegister.componentemir')),
            ],
        ),
        migrations.CreateModel(
            name='FinMir',
            fields=[
                ('id_fin', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255)),
                ('indicador', models.CharField(max_length=255)),
                ('supuesto', models.TextField()),
                ('medio_verificacion', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorActividadMir',
            fields=[
                ('id_indicador_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('supuesto', models.TextField()),
                ('medio_verificacion', models.TextField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='PPRegister.actividadmir')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorComponenteMir',
            fields=[
                ('id_indicador_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('supuesto', models.TextField()),
                ('medio_verificacion', models.TextField()),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='PPRegister.componentemir')),
            ],
        ),
        migrations.CreateModel(
            name='PropositoMir',
            fields=[
                ('id_proposito', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositos', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorPropositoMir',
            fields=[
                ('id_indicador_proposito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('supuesto', models.TextField()),
                ('medio_verificacion', models.TextField()),
                ('id_proposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='PPRegister.propositomir')),
            ],
        ),
    ]
