# Generated by Django 5.2 on 2025-05-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0015_componentemir_actividadmir_finmir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaIndicador',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ficha', models.CharField(choices=[('FIN', 'Indicador Fin'), ('PROPOSITO', 'Indicador Propósito'), ('COMPONENTE', 'Indicador Componente'), ('ACTIVIDAD', 'Indicador Actividad')], max_length=20)),
                ('nombre_indicador', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('definicion', models.TextField(blank=True)),
                ('tipo_indicador', models.CharField(max_length=20)),
                ('algoritmo', models.CharField(blank=True, max_length=255)),
                ('periocidad_calculo', models.CharField(max_length=50)),
                ('dimension_desempeno', models.CharField(blank=True, max_length=255)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='VariableIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('medio_verificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_variable', models.CharField(choices=[('B', 'Variable B'), ('C', 'Variable C'), ('D', 'Variable D (sin medio de verificación)'), ('LBVR', 'Línea base valor de referencia (Total)'), ('META', 'Meta (Total)')], max_length=4)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='PPRegister.fichaindicador')),
            ],
            options={
                'ordering': ['tipo_variable'],
            },
        ),
        migrations.CreateModel(
            name='MetaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('variable', models.OneToOneField(limit_choices_to={'tipo_variable__in': ['B', 'C', 'D', 'META']}, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='PPRegister.variableindicador')),
            ],
        ),
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('variable', models.OneToOneField(limit_choices_to={'tipo_variable__in': ['B', 'C', 'D', 'LBVR']}, on_delete=django.db.models.deletion.CASCADE, related_name='linea_base', to='PPRegister.variableindicador')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fichaindicador',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_ficha', 'FIN')), fields=('id_pp', 'tipo_ficha'), name='unique_fin_per_programa'),
        ),
        migrations.AlterUniqueTogether(
            name='variableindicador',
            unique_together={('id_ficha', 'tipo_variable')},
        ),
    ]
