# Generated by Django 5.2 on 2025-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0016_fichaindicador_variableindicador_metaindicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaindicador',
            name='ambito_medicion',
            field=models.CharField(default='Insumos', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='tendencia',
            field=models.CharField(default='Constantes', max_length=50),
        ),
    ]
