# Generated by Django 5.2 on 2025-05-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0017_fichaindicador_ambito_medicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unidad_medida', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('resultado_estimado', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unidad_resultado', models.CharField(max_length=100)),
                ('fecha_resultado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('medio_verificacion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='metaindicador',
            name='variable',
        ),
        migrations.AlterUniqueTogether(
            name='variableindicador',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variableindicador',
            name='id_ficha',
        ),
        migrations.RemoveConstraint(
            model_name='fichaindicador',
            name='unique_fin_per_programa',
        ),
        migrations.RemoveField(
            model_name='fichaindicador',
            name='algoritmo',
        ),
        migrations.RemoveField(
            model_name='fichaindicador',
            name='id_ficha',
        ),
        migrations.RemoveField(
            model_name='fichaindicador',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='fichaindicador',
            name='periocidad_calculo',
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='periodicidad',
            field=models.CharField(choices=[('anual', 'Anual'), ('bianual', 'Bianual'), ('trianual', 'Trianual'), ('quinquenal', 'Quinquenal'), ('sexenal', 'Sexenal')], default='Anual', max_length=20),
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='tipo_algoritmo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lineabase',
            name='fecha_resultado',
            field=models.DateField(default='2000-02-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineabase',
            name='resultado_estimado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineabase',
            name='unidad_resultado',
            field=models.CharField(default='N/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='ambito_medicion',
            field=models.CharField(choices=[('largo_plazo', 'Resultados a largo plazo'), ('mediano_plazo', 'Resultados a mediano plazo'), ('corto_plazo', 'Resultados a corto plazo'), ('servicios_bienes', 'Servicios/bienes'), ('actividad', 'Actividad'), ('insumos', 'Insumos')], default='Resultados a largo plazo', max_length=50),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='dimension_desempeno',
            field=models.CharField(choices=[('eficacia', 'Eficacia'), ('eficiencia', 'Eficiencia'), ('calidad', 'Calidad'), ('economia', 'Economía')], default='Eficacia', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='tendencia',
            field=models.CharField(choices=[('ascendente', 'Ascendente'), ('descendente', 'Descendente'), ('constante', 'Constante')], default='Ascendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='tipo_ficha',
            field=models.CharField(choices=[('fin', 'Fin'), ('proposito', 'Propósito'), ('componente', 'Componente'), ('actividad', 'Actividad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='tipo_indicador',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('promedio', 'Promedio'), ('variacion_porcentual', 'Variación porcentual'), ('razon', 'Razón'), ('tasa', 'Tasa'), ('indice', 'Índice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='unidad_medida',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='PPRegister.actividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='PPRegister.componente'),
        ),
        migrations.AddField(
            model_name='fichaindicador',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='PPRegister.componente'),
        ),
        migrations.AddField(
            model_name='variable',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='PPRegister.fichaindicador'),
        ),
        migrations.AddField(
            model_name='meta',
            name='variable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='PPRegister.variable'),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='variable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linea_base', to='PPRegister.variable'),
        ),
        migrations.DeleteModel(
            name='MetaIndicador',
        ),
        migrations.DeleteModel(
            name='VariableIndicador',
        ),
    ]
