# Generated by Django 5.2 on 2025-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0018_actividad_componente_meta_variable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='fecha_resultado',
            field=models.DateField(default='2000-02-17'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='fecha_resultado',
            field=models.DateField(default='2000-02-17'),
        ),
    ]
