# Generated by Django 5.2 on 2025-05-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0019_alter_lineabase_fecha_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='fecha',
            field=models.DateField(default='2000-02-17'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='fecha',
            field=models.DateField(default='2000-02-17'),
        ),
    ]
