# Generated by Django 5.2 on 2025-05-20 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0020_alter_lineabase_fecha_alter_meta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='fecha',
            field=models.DateField(default=datetime.date(2000, 2, 17)),
        ),
        migrations.AlterField(
            model_name='meta',
            name='fecha',
            field=models.DateField(default=datetime.date(2000, 2, 17)),
        ),
        migrations.AlterField(
            model_name='meta',
            name='fecha_resultado',
            field=models.DateField(default=datetime.date(2000, 2, 17)),
        ),
    ]
