# Generated by Django 5.2 on 2025-05-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0021_alter_lineabase_fecha_alter_meta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaindicador',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
    ]
