# Generated by Django 5.2 on 2025-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0022_fichaindicador_id_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaindicador',
            name='ambito_medicion',
            field=models.CharField(choices=[('Resultados a largo plazo', 'Resultados a largo plazo'), ('Resultados a mediano plazo', 'Resultados a mediano plazo'), ('Servicios/bienes', 'Servicios/bienes'), ('Servicios/bienes', 'Servicios/bienes'), ('Actividad', 'Actividad'), ('Insumos', 'Insumos')], default='Resultados a largo plazo', max_length=50),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='periodicidad',
            field=models.CharField(choices=[('Anual', 'Anual'), ('Bianual', 'Bianual'), ('Trianual', 'Trianual'), ('Quinquenal', 'Quinquenal'), ('Sexenal', 'Sexenal')], default='Anual', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaindicador',
            name='tendencia',
            field=models.CharField(choices=[('Ascendente', 'Ascendente'), ('Descendente', 'Descendente'), ('Constante', 'Constante')], default='Ascendente', max_length=20),
        ),
    ]
