# Generated by Django 5.2 on 2025-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0023_alter_fichaindicador_ambito_medicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='resultado_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meta',
            name='resultado_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
