# Generated by Django 5.2 on 2025-05-21 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0024_alter_lineabase_resultado_estimado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='numero',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componente',
            name='id_pp',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componente',
            name='numero',
            field=models.CharField(default=57, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.componente'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('componente', 'numero')},
        ),
    ]
