# Generated by Django 5.2 on 2025-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0025_actividad_numero_componente_id_pp_componente_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Consultor'), ('superuser', 'SuperUser')], max_length=10),
        ),
    ]
