# Generated by Django 5.2.1 on 2025-05-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0026_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoCuatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_nivel_ingreso', models.TextField()),
                ('justificacion_nivel_ingreso', models.TextField()),
                ('descripcion_sexo', models.TextField()),
                ('justificacion_sexo', models.TextField()),
                ('descripcion_grupo_etario', models.TextField()),
                ('justificacion_grupo_etario', models.TextField()),
                ('descripcion_lengua_indigena', models.TextField()),
                ('justificacion_lengua_indigena', models.TextField()),
                ('descripcion_ubicacion_geografica', models.TextField()),
                ('justificacion_ubicacion_geografica', models.TextField()),
                ('descripcion_otros_criterios', models.TextField(blank=True, null=True)),
                ('justificacion_otros_criterios', models.TextField(blank=True, null=True)),
                ('id_pp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formato_cuatro', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoDos',
            fields=[
                ('id_formatodos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_programa', models.CharField(max_length=50)),
                ('objetivo', models.TextField()),
                ('poblacion_objetivo', models.TextField()),
                ('bienes_servicios', models.TextField()),
                ('cobertura', models.CharField(max_length=255)),
                ('institucion_coordinadora', models.CharField(max_length=255)),
                ('interdependencia', models.IntegerField(choices=[('complementario', '1= Complementario'), ('dupli', '2= Posible Duplicidad')])),
                ('descripcion_interdependencia', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatodos', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoTres',
            fields=[
                ('id_formatotres', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_actor', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('posicion', models.TextField()),
                ('influencia', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatotres', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoUno',
            fields=[
                ('id_formatouno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('lugar_implementacion', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('poblacion_objetivo', models.TextField()),
                ('bienes_servicios', models.TextField()),
                ('resultados_evaluacion', models.TextField()),
                ('vinculo_documento', models.TextField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='PPRegister.programas_p')),
            ],
        ),
    ]
