# Generated by Django 5.2.1 on 2025-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0027_formatocuatro_formatodos_formatotres_formatouno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatouno',
            name='lugar_implementacion',
            field=models.TextField(),
        ),
    ]
