# Generated by Django 5.2.1 on 2025-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0028_alter_formatouno_lugar_implementacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatodos',
            name='institucion_coordinadora',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formatotres',
            name='influencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formatotres',
            name='posicion',
            field=models.CharField(max_length=255),
        ),
    ]
