# Generated by Django 5.2.1 on 2025-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0029_alter_formatodos_institucion_coordinadora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatodos',
            name='interdependencia',
            field=models.CharField(choices=[('complementario', '1= Complementario'), ('dupli', '2= Posible Duplicidad')]),
        ),
    ]
