# Generated by Django 5.2.1 on 2025-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0030_alter_formatodos_interdependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaindicador',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Bianual', 'Bianual'), ('Trianual', 'Trianual'), ('Quinquenal', 'Quinquenal'), ('Sexenal', 'Sexenal')], default='Anual', max_length=20),
        ),
    ]
