# Generated by Django 5.2.1 on 2025-05-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0031_alter_fichaindicador_periodicidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.AutoField(primary_key=True, serialize=False)),
                ('id_html', models.CharField(max_length=100, unique=True)),
                ('texto', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Causa Indirecta'), (2, 'Causa Directa'), (3, 'Problema Central'), (4, 'Efecto Directo'), (5, 'Efecto Indirecto'), (6, 'Efecto Superior')])),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='PPRegister.nodo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='PPRegister.nodo')),
            ],
        ),
    ]
