# Generated by Django 5.2.1 on 2025-05-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0032_nodo_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='id_pp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='PPRegister.programas_p'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clasificacion',
            field=models.CharField(default='PODER EJECUTIVO', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dependencia',
            field=models.CharField(default='SECRETARIA DE ADMINISTRACIÓ Y FINANZAS', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='siglas',
            field=models.CharField(default='SAF', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Consultor'), ('superuser', 'SuperUser'), ('ultrauser', 'UltraUser')], max_length=10),
        ),
    ]
