# Generated by Django 5.2.1 on 2025-05-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0033_nodo_id_pp_userprofile_clasificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoAO',
            fields=[
                ('id_nodo', models.AutoField(primary_key=True, serialize=False)),
                ('id_html', models.CharField(max_length=100, unique=True)),
                ('texto', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Medio Indirecto'), (2, 'Medio Directo'), (3, 'Solucion problema'), (4, 'Fin Directo'), (5, 'Fin Indirecto'), (6, 'Fin Superior')])),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodosAO', to='PPRegister.programas_p')),
            ],
        ),
        migrations.CreateModel(
            name='ConexionAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='PPRegister.nodoao')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='PPRegister.nodoao')),
            ],
        ),
    ]
