# Generated by Django 5.2.1 on 2025-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0034_nodoao_conexionao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causaindirecta',
            name='id_CD',
        ),
        migrations.RemoveField(
            model_name='efectodirecto',
            name='id_EI',
        ),
        migrations.RemoveField(
            model_name='efectodirecto',
            name='id_PC',
        ),
        migrations.RemoveField(
            model_name='efectoindirecto',
            name='id_ES',
        ),
        migrations.RemoveField(
            model_name='efectosuperior',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='findirecto',
            name='id_FI',
        ),
        migrations.RemoveField(
            model_name='findirecto',
            name='id_SP',
        ),
        migrations.RemoveField(
            model_name='finindirecto',
            name='id_FS',
        ),
        migrations.RemoveField(
            model_name='finsuperior',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='mediodirecto',
            name='id_SP',
        ),
        migrations.RemoveField(
            model_name='medioindirecto',
            name='id_MD',
        ),
        migrations.RemoveField(
            model_name='problemacentral',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='solucionproblema',
            name='id_pp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correo_suplente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correo_titular',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enlace_suplente',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enlace_titular',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clasificacion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dependencia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='siglas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='CausaDirecta',
        ),
        migrations.DeleteModel(
            name='CausaIndirecta',
        ),
        migrations.DeleteModel(
            name='EfectoDirecto',
        ),
        migrations.DeleteModel(
            name='EfectoIndirecto',
        ),
        migrations.DeleteModel(
            name='EfectoSuperior',
        ),
        migrations.DeleteModel(
            name='FinDirecto',
        ),
        migrations.DeleteModel(
            name='FinIndirecto',
        ),
        migrations.DeleteModel(
            name='FinSuperior',
        ),
        migrations.DeleteModel(
            name='MedioDirecto',
        ),
        migrations.DeleteModel(
            name='MedioIndirecto',
        ),
        migrations.DeleteModel(
            name='ProblemaCentral',
        ),
        migrations.DeleteModel(
            name='SolucionProblema',
        ),
    ]
