# Generated by Django 5.2.1 on 2025-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0035_remove_causaindirecta_id_cd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=255)),
                ('poblacion', models.IntegerField(default=0)),
            ],
        ),
    ]
