# Generated by Django 5.2.1 on 2025-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0036_municipios'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteFinanciamineeto',
            fields=[
                ('id_ff', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
