# Generated by Django 5.2.1 on 2025-06-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0037_fuentefinanciamineeto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuenteFinanciamineeto',
            new_name='FuenteFinanciamiento',
        ),
    ]
