# Generated by Django 5.2.1 on 2025-06-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0038_rename_fuentefinanciamineeto_fuentefinanciamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidades', models.PositiveIntegerField(default=0)),
                ('cuantificacion_general', models.PositiveIntegerField(default=0)),
                ('tipo1', models.PositiveIntegerField(default=0)),
                ('tipo2', models.PositiveIntegerField(default=0)),
                ('tipo3', models.PositiveIntegerField(default=0)),
                ('tipo4', models.PositiveIntegerField(default=0)),
                ('tipo5', models.PositiveIntegerField(default=0)),
                ('tipo6', models.PositiveIntegerField(default=0)),
                ('porcentaje1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('porcentaje2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.municipios')),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
            options={
                'unique_together': {('id_municipio', 'id_pp')},
            },
        ),
    ]
