# Generated by Django 5.2.1 on 2025-06-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0039_formato8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formato8',
            new_name='Formato6',
        ),
    ]
