# Generated by Django 5.2.1 on 2025-06-04 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0041_programas_p_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.TextField(blank=True)),
                ('interactua_con', models.TextField(blank=True)),
                ('mecanismo', models.TextField(blank=True)),
                ('responsabilidad', models.TextField(blank=True)),
                ('atribucion', models.TextField(blank=True)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_formato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
