# Generated by Django 5.2.1 on 2025-06-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0042_formato9'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoDoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=255, null=True)),
                ('desagregacion', models.TextField(blank=True, null=True)),
                ('instrumentos', models.TextField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('periodicidad', models.CharField(blank=True, max_length=100, null=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='PPRegister.variable')),
            ],
        ),
    ]
