# Generated by Django 5.2.1 on 2025-06-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0043_formatodoce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatodoce',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatodoce', to='PPRegister.variable'),
        ),
    ]
