# Generated by Django 5.2.1 on 2025-06-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0044_alter_formatodoce_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaindicador',
            name='tipo_indicador',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('promedio', 'Promedio'), ('variacion_porcentual', 'Variación porcentual'), ('razon', 'Razón'), ('tasa', 'Tasa'), ('diferencia', 'Diferencia'), ('indice', 'Índice'), ('conteo', 'Conteo'), ('lugar', 'Lugar'), ('nivel', 'Nivel'), ('promedio_variaciones', 'Promedio móvil de las variaciones de tres años'), ('promedio_tresaños', 'Promedio móvil de tres años'), ('sumatoria', 'Sumatoria')], max_length=50),
        ),
    ]
