# Generated by Django 5.2.1 on 2025-06-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0045_alter_fichaindicador_tipo_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directriz',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='objetivoestrategico',
            name='id_pp',
        ),
        migrations.RemoveField(
            model_name='vertiente',
            name='id_pp',
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='id_vertiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.vertiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vertiente',
            name='id_directriz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.directriz'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='APED',
            fields=[
                ('id_aped', models.AutoField(primary_key=True, serialize=False)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
        migrations.AddField(
            model_name='directriz',
            name='id_aped',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.aped'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='id_aped',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.aped'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vertiente',
            name='id_aped',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.aped'),
            preserve_default=False,
        ),
    ]
