# Generated by Django 5.2.1 on 2025-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0046_remove_directriz_id_pp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacionobjetivo',
            name='cuantificacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poblacionobjetivo',
            name='otros',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
