# Generated by Django 5.2.1 on 2025-06-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0047_poblacionobjetivo_cuantificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(default='', max_length=255),
        ),
    ]
