# Generated by Django 5.2.1 on 2025-06-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0048_userprofile_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoCatorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_2025', models.PositiveIntegerField(default=0)),
                ('meta_2026', models.PositiveIntegerField(default=0)),
                ('meta_2027', models.PositiveIntegerField(default=0)),
                ('meta_2028', models.PositiveIntegerField(default=0)),
                ('meta_2029', models.PositiveIntegerField(default=0)),
                ('meta_2030', models.PositiveIntegerField(default=0)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formato14', to='PPRegister.fichaindicador')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formato14', to='PPRegister.variable')),
            ],
        ),
    ]
