# Generated by Django 5.2.1 on 2025-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0049_formatocatorce'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoTrece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('periodicidad', models.CharField(blank=True, max_length=100)),
                ('responsable_integracion', models.CharField(blank=True, max_length=255)),
                ('es_predeterminado', models.BooleanField(default=False)),
            ],
        ),
    ]
