# Generated by Django 5.2.1 on 2025-06-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0050_formatotrece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentemir',
            name='objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='finmir',
            name='objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propositomir',
            name='objetivo',
            field=models.TextField(),
        ),
    ]
