# Generated by Django 5.2.1 on 2025-06-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0051_alter_componentemir_objetivo_alter_finmir_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatodoce',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatotrece',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formatodoce',
            name='instrumentos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formatodoce',
            name='programa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
