# Generated by Django 5.2.1 on 2025-06-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0052_formatodoce_id_pp_formatotrece_id_pp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocatorce',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuentefinanciamiento',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
    ]
