# Generated by Django 5.2.1 on 2025-06-09 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0053_formatocatorce_id_pp_fuentefinanciamiento_id_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuentefinanciamiento',
            name='id_pp',
        ),
        migrations.CreateModel(
            name='RegistroFormatoDieciciete',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('presupuesto_2025', models.PositiveIntegerField(default=0)),
                ('presupuesto_2026', models.PositiveIntegerField(default=0)),
                ('presupuesto_2027', models.PositiveIntegerField(default=0)),
                ('presupuesto_2028', models.PositiveIntegerField(default=0)),
                ('presupuesto_2029', models.PositiveIntegerField(default=0)),
                ('presupuesto_2030', models.PositiveIntegerField(default=0)),
                ('id_ff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.fuentefinanciamiento')),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
            ],
        ),
    ]
