# Generated by Django 5.2.1 on 2025-06-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0054_remove_fuentefinanciamiento_id_pp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoQuince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('anio_2025', models.CharField(max_length=255)),
                ('anio_2026', models.CharField(max_length=255)),
                ('anio_2027', models.CharField(max_length=255)),
                ('anio_2028', models.CharField(max_length=255)),
                ('anio_2029', models.CharField(max_length=255)),
                ('anio_2030', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormatoDieciseis',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('meta_medianoplazo', models.TextField()),
                ('meta_2025', models.TextField()),
                ('meta_2026', models.TextField()),
                ('meta_2027', models.TextField()),
                ('meta_2028', models.TextField()),
                ('meta_2029', models.TextField()),
                ('meta_2030', models.TextField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formato16', to='PPRegister.componentemir')),
            ],
        ),
        migrations.CreateModel(
            name='Subformato16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_2025', models.PositiveIntegerField(default=0)),
                ('presupuesto_2026', models.PositiveIntegerField(default=0)),
                ('presupuesto_2027', models.PositiveIntegerField(default=0)),
                ('presupuesto_2028', models.PositiveIntegerField(default=0)),
                ('presupuesto_2029', models.PositiveIntegerField(default=0)),
                ('presupuesto_2030', models.PositiveIntegerField(default=0)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subformato16', to='PPRegister.formatodieciseis')),
            ],
        ),
    ]
