# Generated by Django 5.2.1 on 2025-06-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0055_formatoquince_formatodieciseis_subformato16'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoquince',
            name='poblacion_objetivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filas_formato15', to='PPRegister.poblacionobjetivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subformato16',
            name='cog',
            field=models.PositiveIntegerField(choices=[(1000, '1000'), (2000, '2000'), (3000, '3000'), (4000, '4000'), (5000, '5000'), (6000, '6000'), (7000, '7000'), (8000, '8000'), (9000, '9000')], default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2025',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2026',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2027',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2028',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2029',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='anio_2030',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formatoquince',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='formatoquince',
            name='creado_en',
        ),
    ]
