# Generated by Django 5.2.1 on 2025-06-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0056_alter_formatoquince_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formatoquince',
            unique_together=set(),
        ),
    ]
