# Generated by Django 5.2.1 on 2025-06-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0057_alter_formatoquince_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoquince',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
    ]
