# Generated by Django 5.2.1 on 2025-06-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0058_formatoquince_id_pp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormatoQuince',
            new_name='FormatoQuincePoblacion',
        ),
    ]
