# Generated by Django 5.2.1 on 2025-06-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0060_delete_formatoquincepoblacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoQuince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('anio_2025', models.PositiveIntegerField(default=0)),
                ('anio_2026', models.PositiveIntegerField(default=0)),
                ('anio_2027', models.PositiveIntegerField(default=0)),
                ('anio_2028', models.PositiveIntegerField(default=0)),
                ('anio_2029', models.PositiveIntegerField(default=0)),
                ('anio_2030', models.PositiveIntegerField(default=0)),
                ('id_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p')),
                ('poblacion_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_formato15', to='PPRegister.poblacionobjetivo')),
            ],
        ),
    ]
