# Generated by Django 5.2.1 on 2025-06-11 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRegister', '0062_subformato16_id_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subformato16',
            name='id_pp',
        ),
        migrations.AddField(
            model_name='formatodieciseis',
            name='id_pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPRegister.programas_p'),
            preserve_default=False,
        ),
    ]
